//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int Id { get; set; }
        public int IdProduit { get; set; }
        public decimal Total { get; set; }
        public int IdUtilisateur { get; set; }
    
        public virtual Produit Produit { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
